name: CI/CD Backend Express

on:
  push:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Instalar dependências
        run: npm install

    # - name: Testes
    #   run: npm test

  docker-build-push:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push da imagem
        run: |
          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/dnedigitaljsbackend .
          docker push ${{ secrets.DOCKERHUB_TOKEN }}/dnedigitaljsbackend

  deploy-ec2:
    needs: docker-build-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy na AWS EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/dnedigitaljsbackend
            docker stop backend || true
            docker rm backend || true
            docker run -d --name backend -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/dnedigitaljsbackend
